POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}
###
POST http://localhost:3000/login/
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}
###
GET http://localhost:3000/user/tweets/feed/
Authorization: Bearer <YOUR_JWT_TOKEN>

###
GET http://localhost:3000/user/following/
Authorization: Bearer <YOUR_JWT_TOKEN>

###
GET http://localhost:3000/user/followers/
Authorization: Bearer <YOUR_JWT_TOKEN>

###
GET http://localhost:3000/tweets/2/
Authorization: Bearer <YOUR_JWT_TOKEN>

###
GET http://localhost:3000/tweets/2/likes/
Authorization: Bearer <YOUR_JWT_TOKEN>

###
GET http://localhost:3000/tweets/2/replies/
Authorization: Bearer <YOUR_JWT_TOKEN>

###
GET http://localhost:3000/user/tweets/
Authorization: Bearer <YOUR_JWT_TOKEN>

###
POST http://localhost:3000/user/tweets/
Authorization: Bearer <YOUR_JWT_TOKEN>Content-Type: application/json

{
   "tweet": "The Mornings..."
}

###
DELETE http://localhost:3000/tweets/5/
Authorization: Bearer <YOUR_JWT_TOKEN>